// <auto-generated> This file has been auto generated. </auto-generated>

#if !XUNIT_CUSTOM_ENTRYPOINT

module AutoGeneratedEntryPoint

open Xunit.Runner.InProc.SystemConsole

[<EntryPoint>]
let main args =
    ConsoleRunner.Run(args).GetAwaiter().GetResult()

#endif
