' <auto-generated> This file has been auto generated. </auto-generated>

#If Not XUNIT_CUSTOM_ENTRYPOINT Then

Imports Xunit.Runner.InProc.SystemConsole

Public Class AutoGeneratedEntryPoint
	Public Shared Function Main(args As String()) As Integer
		Return ConsoleRunner.Run(args, Nothing, Nothing, Nothing).GetAwaiter().GetResult()
	End Function
End Class

#End If
