// <auto-generated> This file has been auto generated. </auto-generated>

#if !XUNIT_CUSTOM_ENTRYPOINT

using Xunit.Runner.InProc.SystemConsole;

public class AutoGeneratedEntryPoint
{
	public static int Main(string[] args) =>
		ConsoleRunner.Run(args).GetAwaiter().GetResult();
}

#endif
